server:
  port: 8082

spring:
  datasource:
    url: ${PAYMENT_DB_URL}
    username: ${PAYMENT_DB_USER}
    password: ${PAYMENT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resilience4j:
    retry:
      instances:
        orderClient:
          max-attempts: 3
          wait-duration: 500ms

    circuitbreaker:
      instances:
        orderClient:
          sliding-window-size: 10
          minimum-number-of-calls: 5
          failure-rate-threshold: 50
          wait-duration-in-open-state: 5s

logging:
  level:
    dev.maria.payment.service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics