server:
  port: 8081

spring:
  datasource:
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USER}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  cloud:
    consul:
      enabled: false